{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.privatbank",
    "module": "liqpay_x",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "liqpay_x-1.0.aar",
          "url": "liqpay_x-1.0.aar",
          "size": 586350,
          "sha512": "9fc38434f0931220ca3b9b41360a1f3e29da6deaef939259625f21cbf79a5a2856603e1681ec901b7f5526e99d24c0545ec4ed051ee98f1a164c2d7cf249343b",
          "sha256": "d48068ba9ddf66a0934ad2a360dcf3476397b9631cbc80c218bbd83b831c2915",
          "sha1": "a9a030eb64e4b68d8427e3d7f1d99e7660bf2cd1",
          "md5": "5b0e9efe88f6d033c4ed31ca307ac85f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "adapterlibrary",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "confirmcore",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "confirmservice",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "core",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "dynamic-components",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "pbthemes",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "permission-controller",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "ua.privatbank",
          "module": "rxfingerprint",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.21"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "liqpay_x-1.0.aar",
          "url": "liqpay_x-1.0.aar",
          "size": 586350,
          "sha512": "9fc38434f0931220ca3b9b41360a1f3e29da6deaef939259625f21cbf79a5a2856603e1681ec901b7f5526e99d24c0545ec4ed051ee98f1a164c2d7cf249343b",
          "sha256": "d48068ba9ddf66a0934ad2a360dcf3476397b9631cbc80c218bbd83b831c2915",
          "sha1": "a9a030eb64e4b68d8427e3d7f1d99e7660bf2cd1",
          "md5": "5b0e9efe88f6d033c4ed31ca307ac85f"
        }
      ]
    }
  ]
}
