{
  "formatVersion": "1.1",
  "component": {
    "group": "ua.privatbank",
    "module": "confirmcore",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "confirmcore-1.0.aar",
          "url": "confirmcore-1.0.aar",
          "size": 514345,
          "sha512": "d30ef7efa2ff92f1cd3386c9d610643afe2a91edda6ce2a4634fe6e170154330fa7e4a9cab1a4569bc0caac229f385d32b84bd1fc1401cd96e7fe761e9be4779",
          "sha256": "0f385bbde657e9a7ae381de8b908384d1a46b8fed4d167a3d5de78e5b1415329",
          "sha1": "25a3a6b77124cef8b116c0c4157c931cce58cc34",
          "md5": "692d76e65a727b00706e202b4869af1c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.7.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "ua.privatbank",
          "module": "core",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "ua.privatbank",
          "module": "rxfingerprint",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "ua.privatbank",
          "module": "dynamic-components",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "p24core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "confirmcore-1.0.aar",
          "url": "confirmcore-1.0.aar",
          "size": 514345,
          "sha512": "d30ef7efa2ff92f1cd3386c9d610643afe2a91edda6ce2a4634fe6e170154330fa7e4a9cab1a4569bc0caac229f385d32b84bd1fc1401cd96e7fe761e9be4779",
          "sha256": "0f385bbde657e9a7ae381de8b908384d1a46b8fed4d167a3d5de78e5b1415329",
          "sha1": "25a3a6b77124cef8b116c0c4157c931cce58cc34",
          "md5": "692d76e65a727b00706e202b4869af1c"
        }
      ]
    }
  ]
}
